version: '3.8'

services:
  chrome_remote:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
  tests:
    build: .
    volumes: 
      - ./build/reports/:/home/gradle/build/reports/

    command: >
      bash -c "./runTests.sh"
#    ["gradle test && gradle allureReport"]
#     command: gradle allureReport
    # command: ["./wait-for-it.sh", "chrome_remote:4444",]
    depends_on: 
      - chrome_remote

